Draft: Feature/select component
yoru-ui/yoru-ui pull request #46
Opened 2022-12-04 01:09 UTC by justirva09

close #45

2022-12-16 16:57 UTC, leonardmns12 commented
@justirva09 ini masih draft? bukannya tadi udah di open ya?

2022-12-26 08:03 UTC, leonardmns12 requested changes

2022-12-26 08:03 UTC, leonardmns12 commented on packages/select/src/BaseSelect/SingleSelect.tsx
> +    const hiddenStyle = value ? { visibility: 'hidden' as const } : undefined;
ini udah ga perlu lagi sih, kan diatas udah di cek kalo `value` nya null bakal di return.

2022-12-26 08:03 UTC, leonardmns12 commented on packages/select/src/BaseSelect/MultiSelect.tsx
> +    const hiddenStyle = value?.length !== 0 ? { visibility: 'hidden' as const } : undefined;
ini better dibuat kaya yang di `SingleSelect.tsx`, kalo valuenya ada langsung di return aja.

2022-12-26 08:06 UTC, leonardmns12 commented
@justirva09 ini udah gw repiww ya lort, agak banyak poin nya tapi changes nya cuma dikit aja kok, kalo ada something let me know ya.

2022-12-26 11:37 UTC, justirva09 commented
> @justirva09 ini udah gw repiww ya lort, agak banyak poin nya tapi changes nya cuma dikit aja kok, kalo ada something let me know ya.

noted, thank yu for the ripiw.. to be updated later ya @leonardmns12

2022-12-31 02:12 UTC, justirva09 commented on packages/select/src/BaseSelect/SingleSelect.tsx
> +    const hiddenStyle = value ? { visibility: 'hidden' as const } : undefined;
wkwk ga fokus lort

2022-12-31 02:50 UTC, leonardmns12 approved these changes
mantabzzz

2022-12-31 02:50 UTC, merged